### ISSUE TITLE
Threshold of attempts

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/antiscan#4]
Thanks for pointing me to this module! One thing that [Path2Ban](https://github.com/backdrop-contrib/path2ban) had that I found useful was the ability to set a threshold number of attempts before blocking occurred -- e.g. the defaults were 5 attempts to any forbidden path within an hour. This means that someone who tries one URL out of curiousity, or mis-types a path once, will not be blocked immediately.

What do you think about that type of setting?

**Comment by findlabnet** [comment]
This module is not about human interaction, only against bad robots.
From my long time monitoring for activity of such scanners, they do not often try the same path more than once per attempt, but different paths at the same time or within a short period of time, e.g. `/simple.php, /sellers.json, /settings.json` and so on simultaneously. 

Since all such blocked attempts (from some of my sites) have been reported to AbuseIPDB, you can easily verify - there are no humans, [only bots](https://www.abuseipdb.com/user/52177).

Besides, if someone tries to visit restricted URL out of curiosity - this person should know how to change his compromised IP ;-).

Anyway, the module provides option to automatically unblock blocked IPs after some time: 1, 7, 30 or 365 days. 
Maybe it would be worth to add some shorter periods like 5 minutes or 1 hour?

**Comment by laryn** [comment]
An immediate block after 1 attempt seems harsh -- but to your concern, I think that Path2Ban tracks attempts to any blocked path, not necessarily the same one, within a short period of time. I'm just thinking of times when I visit a site and I'm trying to determine which CMS it is using, sometimes I'll try a known path just as a quick check. I'd feel more comfortable with an option to warn for the first attempt, or something along those lines.

A shorter unblock time limit option could also potentially be useful.

**Comment by findlabnet** [comment]
> I'm trying to determine which CMS it is using, 

When I try to determine which CMS is in use - I just press Ctrl+U (View page source) because I personally prefer less interaction with site where I'm not sure what it is. (And this site will open in a new private / incognito window with javascript disabled.)

> option to warn for the first attempt

One researcher among 10000 bots?
Less relevant (to me) if more than one or two sites need to be protected.

**Comment by findlabnet** [comment]
So, I've added shorter unblocking time limit options and a note on the admin screen about module behavior.
I think that should be enough for now.
A threshold is inappropriate here in my opinion - have you ever seen a mousetrap with a second chance?
Thanks for your interest and suggestions.

**Comment by laryn** [comment]
I respect your position but I'm personally considering locations with many people sharing an IP and I do not want to potentially increase site admin overhead -- for example, having to field calls and go in and manually unblock when somebody blocks the shared IP after one attempt to check a Wordpress URL.

**Comment by findlabnet** [comment]
I think I can add this feature as an option.

**Comment by laryn** [comment]
I believe Path2Ban does this using the Flood Control mechanism. (`flood_is_allowed()`, `flood_register_event()`, etc.)

**Comment by findlabnet** [comment]
Yes, Path2Ban does this using the Flood Control mechanism.
>I think I can add this feature **as an option**.

So, when/if this option is enabled - any threshold limit and window can be set.

**Comment by findlabnet** [comment]
[Done](https://github.com/backdrop-contrib/antiscan/releases/tag/1.x-1.0.11)

**Comment by laryn** [comment]
Amazing, thanks! I will try this out.

**Comment by findlabnet** [comment]
@laryn, I would like to know if you are satisfied with the realization of your request?

**Comment by laryn** [comment]
@findlabnet Yes, I believe so! If any issues arise in the future I'll open a ticket. Thanks again.
